-- ============================================================
--  striano_fastmenu - server/main.lua
--  (arquivo de servidor — sem lógica, apenas placeholder)
-- ============================================================
